CREATE TABLE medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    record_code VARCHAR(20) NOT NULL UNIQUE,

    patient_id BIGINT NOT NULL,

    doctor_id BIGINT NOT NULL,

    appointment_id BIGINT,

    record_type VARCHAR(30) NOT NULL
        CHECK (
            record_type IN (
                'CONSULTATION',
                'FOLLOW_UP',
                'DIAGNOSIS',
                'TREATMENT',
                'PROCEDURE',
                'DISCHARGE'
            )
        ),

    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    chief_complaint TEXT,

    symptoms TEXT,

    examination_notes TEXT,

    diagnosis TEXT,

    treatment_plan TEXT,

    clinical_notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_medical_records_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id),

    CONSTRAINT fk_medical_records_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(id),

    CONSTRAINT fk_medical_records_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointments(id)
);