CREATE TABLE patient_vitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id BIGINT NOT NULL,

    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    temperature_celsius DECIMAL(4,1)
        CHECK (
            temperature_celsius IS NULL
            OR temperature_celsius BETWEEN 25.0 AND 45.0
        ),

    heart_rate_bpm INTEGER
        CHECK (
            heart_rate_bpm IS NULL
            OR heart_rate_bpm BETWEEN 20 AND 250
        ),

    systolic_bp_mmhg INTEGER
        CHECK (
            systolic_bp_mmhg IS NULL
            OR systolic_bp_mmhg BETWEEN 50 AND 300
        ),

    diastolic_bp_mmhg INTEGER
        CHECK (
            diastolic_bp_mmhg IS NULL
            OR diastolic_bp_mmhg BETWEEN 20 AND 200
        ),

    respiratory_rate_bpm INTEGER
        CHECK (
            respiratory_rate_bpm IS NULL
            OR respiratory_rate_bpm BETWEEN 5 AND 80
        ),

    oxygen_saturation_percent DECIMAL(5,2)
        CHECK (
            oxygen_saturation_percent IS NULL
            OR oxygen_saturation_percent BETWEEN 50.00 AND 100.00
        ),

    blood_glucose_mg_dl DECIMAL(6,2)
        CHECK (
            blood_glucose_mg_dl IS NULL
            OR blood_glucose_mg_dl BETWEEN 20.00 AND 1000.00
        ),

    height_cm DECIMAL(5,2)
        CHECK (
            height_cm IS NULL
            OR height_cm BETWEEN 30.00 AND 250.00
        ),

    weight_kg DECIMAL(6,2)
        CHECK (
            weight_kg IS NULL
            OR weight_kg BETWEEN 1.00 AND 500.00
        ),

    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_vitals_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id)
);