CREATE TABLE prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prescription_code VARCHAR(20) NOT NULL UNIQUE,

    patient_id BIGINT NOT NULL,

    doctor_id BIGINT NOT NULL,

    medical_record_id BIGINT,

    medication_name VARCHAR(150) NOT NULL,

    dosage VARCHAR(100),

    frequency VARCHAR(100),

    route VARCHAR(50),

    duration_days INTEGER
        CHECK (
            duration_days IS NULL
            OR duration_days > 0
        ),

    quantity VARCHAR(50),

    instructions TEXT,

    prescribed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (
            status IN (
                'ACTIVE',
                'COMPLETED',
                'CANCELLED'
            )
        ),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_prescriptions_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id),

    CONSTRAINT fk_prescriptions_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(id),

    CONSTRAINT fk_prescriptions_medical_record
        FOREIGN KEY (medical_record_id)
        REFERENCES medical_records(id)
);