CREATE TABLE wards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ward_code VARCHAR(20) NOT NULL UNIQUE,

    name VARCHAR(100) NOT NULL,

    ward_type VARCHAR(30) NOT NULL
        CHECK (
            ward_type IN (
                'GENERAL',
                'ICU',
                'EMERGENCY',
                'PEDIATRIC',
                'MATERNITY',
                'SURGICAL',
                'ISOLATION'
            )
        ),

    department_id BIGINT NOT NULL,

    floor VARCHAR(30),

    capacity INTEGER NOT NULL
        CHECK (capacity > 0),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_wards_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
);