CREATE TABLE emergencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    emergency_code VARCHAR(20) NOT NULL UNIQUE,

    patient_id BIGINT NOT NULL,

    doctor_id BIGINT,

    department_id BIGINT NOT NULL,

    arrival_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    chief_complaint VARCHAR(255),

    triage_level VARCHAR(20) NOT NULL
        CHECK (
            triage_level IN (
                'RESUSCITATION',
                'EMERGENCY',
                'URGENT',
                'LESS_URGENT',
                'NON_URGENT'
            )
        ),

    status VARCHAR(20) NOT NULL DEFAULT 'OPEN'
        CHECK (
            status IN (
                'OPEN',
                'UNDER_TREATMENT',
                'ADMITTED',
                'DISCHARGED',
                'LEFT_WITHOUT_TREATMENT'
            )
        ),

    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_emergencies_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id),

    CONSTRAINT fk_emergencies_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(id),

    CONSTRAINT fk_emergencies_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
);