CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT,

    action VARCHAR(30) NOT NULL
        CHECK (
            action IN (
                'CREATE',
                'UPDATE',
                'DELETE',
                'LOGIN',
                'LOGOUT',
                'VIEW'
            )
        ),

    entity_type VARCHAR(50) NOT NULL,

    entity_id BIGINT,

    description TEXT,

    ip_address INET,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);