CREATE TABLE doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    doctor_code VARCHAR(20) NOT NULL UNIQUE,

    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,

    specialization VARCHAR(100) NOT NULL,

    license_number VARCHAR(50) NOT NULL UNIQUE,

    phone VARCHAR(20),
    email VARCHAR(255),

    department_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_doctors_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
);