CREATE TABLE beds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    bed_code VARCHAR(30) NOT NULL UNIQUE,

    ward_id BIGINT NOT NULL,

    bed_type VARCHAR(30) NOT NULL
        CHECK (
            bed_type IN (
                'GENERAL',
                'ICU',
                'EMERGENCY',
                'ISOLATION',
                'MATERNITY',
                'PEDIATRIC'
            )
        ),

    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
        CHECK (
            status IN (
                'AVAILABLE',
                'OCCUPIED',
                'MAINTENANCE',
                'OUT_OF_SERVICE'
            )
        ),

    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_beds_ward
        FOREIGN KEY (ward_id)
        REFERENCES wards(id)
);