CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    appointment_code VARCHAR(20) NOT NULL UNIQUE,

    patient_id BIGINT NOT NULL,

    doctor_id BIGINT NOT NULL,

    department_id BIGINT NOT NULL,

    start_at TIMESTAMP WITH TIME ZONE NOT NULL,

    end_at TIMESTAMP WITH TIME ZONE NOT NULL,

    reason VARCHAR(255),

    notes TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
        CHECK (
            status IN (
                'SCHEDULED',
                'CONFIRMED',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELLED',
                'NO_SHOW'
            )
        ),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_appointments_time
        CHECK (end_at > start_at),

    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id),

    CONSTRAINT fk_appointments_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(id),

    CONSTRAINT fk_appointments_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
);