CREATE TABLE admissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    admission_code VARCHAR(20) NOT NULL UNIQUE,

    patient_id BIGINT NOT NULL,

    doctor_id BIGINT NOT NULL,

    bed_id BIGINT,

    emergency_id BIGINT,

    admission_type VARCHAR(30) NOT NULL
        CHECK (
            admission_type IN (
                'EMERGENCY',
                'ELECTIVE',
                'TRANSFER',
                'OBSERVATION'
            )
        ),

    admitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    expected_discharge_at TIMESTAMP WITH TIME ZONE,

    discharged_at TIMESTAMP WITH TIME ZONE,

    discharge_summary TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (
            status IN (
                'ACTIVE',
                'DISCHARGED',
                'CANCELLED'
            )
        ),

    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_admissions_discharge_time
        CHECK (
            discharged_at IS NULL
            OR discharged_at >= admitted_at
        ),

    CONSTRAINT fk_admissions_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id),

    CONSTRAINT fk_admissions_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(id),

    CONSTRAINT fk_admissions_bed
        FOREIGN KEY (bed_id)
        REFERENCES beds(id),

    CONSTRAINT fk_admissions_emergency
        FOREIGN KEY (emergency_id)
        REFERENCES emergencies(id)
);