spring.application.name=mediops-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mediops_db
spring.datasource.username=postgres
spring.datasource.password=VK@5432

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true